export const coreSeedUsers = [
  {
    id: 'u1',
    name: 'Maya Quinn',
    username: 'mayaquinn',
    email: 'maya@optizenqor.app',
    avatar: 'https://placehold.co/120x120',
    bio: 'Creator building social products that feel fast, calm, and human.',
    role: 'Creator',
    verification: 'Verified',
    status: 'Active',
    followers: 82300,
    following: 421,
    walletSummary: '$1,280 pending payout',
    health: 'No active flags. Reel engagement rising 18%.',
    reports: '2 resolved, 0 open',
    lastActive: '2m ago',
    emailVerified: true,
    blocked: false,
    password: '123456',
  },
  {
    id: 'u2',
    name: 'Nexa Studio',
    username: 'nexa.studio',
    email: 'studio@nexa.app',
    avatar: 'https://placehold.co/120x120',
    bio: 'Business account for campaigns, brand drops, and marketplace launches.',
    role: 'Business',
    verification: 'Verified',
    status: 'Active',
    followers: 15400,
    following: 184,
    walletSummary: '$940 ad credit',
    health: 'Campaign delivery normal. No sanctions.',
    reports: '1 open report on ad caption',
    lastActive: '10m ago',
    emailVerified: true,
    blocked: false,
    password: '123456',
  },
  {
    id: 'u3',
    name: 'Rafi Ahmed',
    username: 'rafiahmed',
    email: 'rafi@optizenqor.app',
    avatar: 'https://placehold.co/120x120',
    bio: 'General user exploring stories, events, and chats.',
    role: 'User',
    verification: 'Pending',
    status: 'Review',
    followers: 9700,
    following: 283,
    walletSummary: 'No monetization enabled',
    health: 'Login from new device. Security note added.',
    reports: '0 open reports',
    lastActive: '36m ago',
    emailVerified: true,
    blocked: false,
    password: '123456',
  },
  {
    id: 'u4',
    name: 'Luna Crafts',
    username: 'luna.crafts',
    email: 'luna@crafts.shop',
    avatar: 'https://placehold.co/120x120',
    bio: 'Seller storefront for handmade drops and seasonal collections.',
    role: 'Seller',
    verification: 'Verified',
    status: 'Active',
    followers: 21400,
    following: 129,
    walletSummary: '$2,410 available',
    health: 'Storefront healthy. One refund loop under review.',
    reports: '1 commerce-related ticket',
    lastActive: '5m ago',
    emailVerified: true,
    blocked: false,
    password: '123456',
  },
  {
    id: 'u5',
    name: 'Arif Talent Hub',
    username: 'arif.talent',
    email: 'ops@talenthub.io',
    avatar: 'https://placehold.co/120x120',
    bio: 'Recruiting and hiring account with community job posts.',
    role: 'Recruiter',
    verification: 'Eligible',
    status: 'Suspended',
    followers: 6400,
    following: 92,
    walletSummary: '$120 boost credit',
    health: 'Temporarily restricted pending verification document check.',
    reports: '3 impersonation-related reports',
    lastActive: '1h ago',
    emailVerified: true,
    blocked: false,
    password: '123456',
  },
];

export const coreSeedFollows = [
  { followerId: 'u1', targetId: 'u4' },
  { followerId: 'u3', targetId: 'u1' },
];

export const coreSeedPosts = [
  {
    id: 'p1',
    authorId: 'u1',
    caption: 'Building social products that feel fast, calm, and human.',
    media: ['https://placehold.co/800x600'],
    tags: ['product', 'design', 'social'],
    likes: 2300,
    comments: 2,
    shares: 54,
    views: 9200,
    status: 'Visible',
    type: 'post',
    createdAt: '2026-04-19T14:40:00.000Z',
  },
  {
    id: 'p2',
    authorId: 'u2',
    caption: 'Which launch card style performs best?',
    media: ['https://placehold.co/800x600'],
    tags: ['launch', 'brand'],
    likes: 1800,
    comments: 82,
    shares: 41,
    views: 7600,
    status: 'Featured',
    type: 'post',
    createdAt: '2026-04-19T12:20:00.000Z',
  },
];

export const coreSeedPostReactions = [
  {
    postId: 'p1',
    userId: 'u2',
    reaction: 'like',
    createdAt: '2026-04-19T14:50:00.000Z',
  },
  {
    postId: 'p1',
    userId: 'u4',
    reaction: 'fire',
    createdAt: '2026-04-19T15:12:00.000Z',
  },
];

export const coreSeedPostComments = [
  {
    id: 'pc1',
    postId: 'p1',
    authorId: 'u4',
    author: 'Luna Crafts',
    message: 'This rollout feels very polished.',
    replyTo: null,
    createdAt: '2026-04-19T15:00:00.000Z',
    likeCount: 12,
    isLikedByMe: true,
    isReported: false,
    isEdited: false,
    mentions: [],
  },
  {
    id: 'pc2',
    postId: 'p1',
    authorId: 'u3',
    author: 'Rafi Ahmed',
    message: 'Would love to see the admin side too.',
    replyTo: 'pc1',
    createdAt: '2026-04-19T15:03:00.000Z',
    likeCount: 3,
    isLikedByMe: false,
    isReported: false,
    isEdited: false,
    mentions: ['mayaquinn'],
  },
];

export const coreSeedCommentReactions = [
  { commentId: 'pc1', userId: 'u1', reaction: 'like', createdAt: '2026-04-19T15:01:00.000Z' },
  { commentId: 'pc1', userId: 'u2', reaction: 'fire', createdAt: '2026-04-19T15:02:00.000Z' },
  { commentId: 'pc2', userId: 'u1', reaction: 'like', createdAt: '2026-04-19T15:04:00.000Z' },
];

export const coreSeedThreads = [
  {
    id: 't1',
    title: 'Creator Collab Group',
    participantIds: ['u1', 'u2', 'u3'],
    participantsLabel: '6 members',
    flag: 'Abuse report',
    summary: 'Two users escalated a creator collaboration dispute.',
  },
  {
    id: 't2',
    title: 'Buyer and Seller Support',
    participantIds: ['u3', 'u4'],
    participantsLabel: '2 members',
    flag: 'Refund conflict',
    summary: 'Buyer accuses seller of false shipment update.',
  },
];

export const coreSeedMessages = [
  {
    id: 'm1',
    threadId: 't1',
    senderId: 'u1',
    text: 'Please remove the clip before reposting it.',
    read: true,
    timestamp: '2026-04-19T15:00:00.000Z',
    attachments: [],
    replyToMessageId: null,
    deliveryState: 'read',
    kind: 'text',
    mediaPath: null,
  },
  {
    id: 'm2',
    threadId: 't1',
    senderId: 'u3',
    text: 'I can use whatever I want.',
    read: false,
    timestamp: '2026-04-19T15:01:00.000Z',
    attachments: [],
    replyToMessageId: null,
    deliveryState: 'delivered',
    kind: 'text',
    mediaPath: null,
  },
  {
    id: 'm3',
    threadId: 't2',
    senderId: 'u3',
    text: 'Tracking says delivered but I received nothing.',
    read: true,
    timestamp: '2026-04-19T14:00:00.000Z',
    attachments: [],
    replyToMessageId: null,
    deliveryState: 'read',
    kind: 'text',
    mediaPath: null,
  },
];

export const coreSeedNotifications = [
  {
    id: 'n1',
    recipientId: 'u1',
    title: 'Your reel is trending',
    body: 'Engagement is up 18% in the last hour.',
    createdAt: '2026-04-19T15:30:00.000Z',
    read: false,
    type: 'social',
    routeName: '/reels',
    entityId: 'r1',
    metadata: { source: 'trending_engine' },
  },
  {
    id: 'n2',
    recipientId: 'u1',
    title: 'Payout pending review',
    body: 'Your latest withdrawal is awaiting approval.',
    createdAt: '2026-04-19T14:35:00.000Z',
    read: true,
    type: 'commerce',
    routeName: '/wallet-payments',
    entityId: 'txn-1002',
    metadata: { status: 'pending' },
  },
];
