import { randomUUID } from 'crypto';

export type IdPrefix =
  | 'user'
  | 'story'
  | 'post'
  | 'job'
  | 'application'
  | 'event'
  | 'community'
  | 'page'
  | 'product'
  | 'wallet'
  | 'bookmark'
  | 'upload'
  | 'comment'
  | 'reaction'
  | 'reel'
  | 'draft'
  | 'scheduled'
  | 'like'
  | 'share'
  | 'order'
  | 'report'
  | 'thread'
  | 'session'
  | 'notification'
  | 'message'
  | 'conversation'
  | 'buddy_request'
  | 'buddy_relation'
  | 'call_session'
  | 'call_signal'
  | 'collection'
  | 'collection_item'
  | 'campaign'
  | 'txn'
  | 'subscription'
  | 'chat_pref'
  | 'archive'
  | 'hidden'
  | 'live_stream'
  | 'live_comment'
  | 'live_reaction'
  | 'support_faq'
  | 'ticket'
  | 'support_conversation'
  | 'support_message'
  | 'offer';

export function makeId<T extends IdPrefix>(prefix: T): `${T}_${string}` {
  return `${prefix}_${randomUUID().replace(/-/g, '')}` as `${T}_${string}`;
}
